### ISSUE TITLE
Different Secret Chronicles Images for More Posts on Forum...

### ISSUE THREAD

**Issue by datahead8888** [Quintus/chessboard#10]
This was one of my favorite features of the old SMC forums.

As you made more posts, your rank would increase, causing you to progress through images of different SMC enemies. It also had icons for "Team", "Admin", and "MVP".

However, if we add icons for the last 3 team statuses, I'd still like to see the Secret Chronicles enemies displayed for the number of posts - it was disappointing to see this disappear after being granted "Team" status.

I imagine this task is a matter of Ruby scripting for the forum code. It would be useful to make it configurable through the website itself if possible, though.

--Obviously the images displayed for the number of posts and the team ranks must be configurable, since this forum software may be used for non gaming websites down the road.

**Comment by Luiji** [comment]
@datahead8888 That image thing is also what encouraged me to spam the hell out of the forums when I first got there.

**Comment by datahead8888** [comment]
Anything that encourages forum involvement for people is a good thing :)

I would have considered trying to code this, but my Ruby and Sinatra skills are very limited right now (and I don't always get much time).  If you get a chance to code this, Luiji, it will be greatly appreciated.  If we get enough things like this implemented, this software could eventually compete head-to-head with phpBB on the Internet.

**Comment by Luiji** [comment]
@datahead8888 "Spam" is, by definition, not a good thing. I'd concede that perhaps our user group will be intelligent enough not to over post to increase post count, or perhaps that we can mitigate the risk the same way it happened with me (a private message from Crabmaster, I believe).

Nonetheless, this isn't a feature that I'd particularly endorse at this time so you won't see me coding it any time soon. ;)

**Comment by datahead8888** [comment]
> "Spam" is, by definition, not a good thing.

I had assumed you were exaggerating.  This feature does, however, encourage people to get involved in discussions.  If they're posting useful input, that is a good thing.  My main motivation for getting involved in forums in the last year was to show activity in the forums and try to get people ultimately contributing.

> Nonetheless, this isn't a feature that I'd particularly endorse at this time

Do you think it just isn't as much of a priority against other tasks?  I was just interested in your thought process.

**Comment by Quintus** [comment]
Interesting. I would never have tought about this as something engaging people into discussions. To be honest, I rather thought ranking encourages, well, spamming. I might be wrong on this end, though. Try to convince me :-)

Also, please note that Chessboard already has a functionality that allows the administrator to manually set the forum status of a member, I’ve just not used it. The forum itself prints "Administrator" or "Moderator" below a username depending on the privileges ("Member" if no privileges), but the admin can override this for specific users with anything he likes. I was wanting to tag everyone from the team as "Developer", "Artist", etc. or so when the forum grows, but currently that would mean tagging all the persons that are on the forum, which is nonsense.

The forum also already has a posts counter below each user’s name, so it’s up to the viewer to make something of that value.

Also, feel free to at-mention me when you file a ticket against chessboard or any other repository that is not the main TSC repo, because for unknown reasons I don’t get notifications if someone opens a ticket.

Vale,
Quintus

**Comment by datahead8888** [comment]
These are the reasons why I think it might be useful to have this feature:
* We've had a problem with getting people to use the forum generally.  At one point we considered moving to the mailing list because most people didn't use the forum.  Even now, I find it easier to find an excuse to make a new GitHub ticket for something like "The name of the villain" than to depend on a forum posting to get feedback.
* It helps add to the fun feel of the site.  The SMC forums were very visual.  Obviously, adding a partial screenshot toward the top of the page and forum posting icons are other things we should consider, but having a graphic for the number of postings helps add to this feel, too.  SMC used to be a bustling forum.  Part of that was probably due to the fact that the bug tracking was done through the forum, but I think visual features like this helped, too.
* secretmaryo.org is not the only site that I've seen use this feature.  Other sites that use Chessboard down the line may be interested in the feature.  We could allow it to be turned on/off by a site administrator.
* If people are posting useful input, I don't see a problem with more posts.  If they start making necro posts or off topic posts (outside of the normal off topic forum or in excessive number), we would just warn them about the forum rules, as Luiji said.

**Comment by Quintus** [comment]
Closing as I don't maintain this anymore.
